### ISSUE TITLE
Eclipse fails to start after some manipulations of plugins

### ISSUE THREAD

**Issue by wiresketch** [flathub/org.eclipse.Java#100]
I suspect that I discovered a p2 issue that affects the Flatpak distribution of Eclipse. Doing some steps can break the installation and it cannot be repaired even using "-clean" argument, at least this is what happens in my case. I suspect this is a p2 problem so I've filed the issue there. Please see the referred issue for more details:
https://github.com/eclipse-equinox/p2/issues/555

Perhaps others can try the outlined steps and confirm that the issue is reproducible.

**Comment by Mailaender** [comment]
It is reproducible and I don't have a workaround for it which makes it quite serious as there is no way to install the Plug-in Developer tools for example. Changing the timestamp of `eclipse.ini` does not fix it. Only deleting `.eclipse` and starting without plugins works.

**Comment by Mailaender** [comment]
It shows a stack trace with not too much information:
```
!ENTRY org.eclipse.osgi 4 0 2025-03-08 06:30:19.530
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:86)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
```

`rm -rf ~/.var/app/org.eclipse.Java/` brings it back to a state where it starts and plug-ins can be reinstalled.
