### ISSUE TITLE
Eclipse breaks on update

### ISSUE THREAD

**Issue by bullfroggie** [flathub/org.eclipse.Java#12]
After updating Eclipse, it fails to start afterwards.
This is the [error message](https://imgur.com/W18be3K) that is displayed when launching Eclipse.
Here's [the log](https://gist.github.com/bullfroggie/1882f936e53f20245e8de7c23388550e) that is mentioned in the error message. 

**OS**: Pop!_OS 20.04

**Comment by mbooth101** [comment]
Thanks for the report; running ```flatpak run org.eclipse.Java -clean``` is what I would have suggested too.

**Comment by mauromol** [comment]
Also updating from 2020-06 to 2020-09 requires `-clean` otherwise Eclipse won't start.

**Comment by Mailaender** [comment]
It shows a stack trace with not too much information:
```
!ENTRY org.eclipse.osgi 4 0 2025-03-08 06:30:19.530
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:86)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
```

`rm -rf ~/.var/app/org.eclipse.Java/` brings it back to a state where it starts and plug-ins can be reinstalled.

**Comment by Mailaender** [comment]
See also https://github.com/flathub/org.eclipse.Java/issues/100
